create table smallwork (
	id_ INTEGER not null primary key,
	quoteReference VARCHAR(75) null,
	projectName VARCHAR(75) null,
	customerAddress VARCHAR(75) null,
	workType VARCHAR(75) null,
	leadSource VARCHAR(75) null,
	productSpecific VARCHAR(75) null,
	description VARCHAR(75) null,
	customerName VARCHAR(75) null,
	postcode VARCHAR(75) null,
	sitename VARCHAR(75) null,
	lead VARCHAR(75) null,
	location VARCHAR(75) null,
	enduser VARCHAR(75) null,
	contactName VARCHAR(75) null,
	phone INTEGER,
	email VARCHAR(75) null,
	projectDate VARCHAR(75) null,
	anticipatedDate VARCHAR(75) null,
	endDate VARCHAR(75) null,
	endDate2 VARCHAR(75) null,
	bidInfor VARCHAR(75) null,
	quotationName VARCHAR(75) null,
	projectCost INTEGER,
	dateShowOnQuote VARCHAR(75) null,
	projectSell INTEGER,
	quoteSubmitDate VARCHAR(75) null,
	winProbability VARCHAR(75) null,
	stage VARCHAR(75) null
);

create table statusofsubmittedquote (
	sosqId LONG not null primary key,
	sosq VARCHAR(75) null,
	winprob VARCHAR(75) null,
	aorderdate VARCHAR(75) null,
	ppstartdate VARCHAR(75) null,
	ppenddate VARCHAR(75) null,
	createDate VARCHAR(75) null,
	customercomittype VARCHAR(75) null,
	upload VARCHAR(75) null,
	pon LONG,
	valueofcommit LONG,
	rmethod VARCHAR(75) null,
	rdate VARCHAR(75) null,
	pcdc VARCHAR(75) null,
	onwhatbasis VARCHAR(75) null,
	recordproposedcourse VARCHAR(75) null,
	comments VARCHAR(75) null,
	currrentId INTEGER
);